// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SakaryaERP.Data;

#nullable disable

namespace SakaryaERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724102500_AlisTalepTeklifSiparisIskonto")]
    partial class AlisTalepTeklifSiparisIskonto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisFaturasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AlisIrsaliyesiId")
                        .HasColumnType("integer");

                    b.Property<int?>("AlisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisIrsaliyesiId");

                    b.HasIndex("AlisSiparisiId");

                    b.HasIndex("CariId");

                    b.ToTable("AlisFaturalari");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisFaturasiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisFaturasiId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisFaturasiId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("AlisFaturasiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisIrsaliyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AlisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisSiparisiId");

                    b.HasIndex("CariId");

                    b.HasIndex("SubeId");

                    b.ToTable("AlisIrsaliyeleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisIrsaliyesiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisIrsaliyesiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisIrsaliyesiId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("AlisIrsaliyesiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisSiparisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AlisTeklifiId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SiparisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisTeklifiId");

                    b.HasIndex("CariId");

                    b.HasIndex("SubeId");

                    b.ToTable("AlisSiparisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisSiparisiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisSiparisiId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("AlisSiparisiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TalepNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("AlisTalepleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTeklifi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AlisTalebiId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisTalebiId");

                    b.HasIndex("CariId");

                    b.ToTable("AlisTeklifleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTeklifiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlisTeklifiId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisTeklifiId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("AlisTeklifiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SakaryaERP.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("SubeId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SubeId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SakaryaERP.Models.BankaHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("HesapAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IBAN")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BankaHesaplari");
                });

            modelBuilder.Entity("SakaryaERP.Models.Cari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("CariKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CariTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KrediLimiti")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VergiNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CariKodu")
                        .IsUnique();

                    b.ToTable("Cariler");
                });

            modelBuilder.Entity("SakaryaERP.Models.CariFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("BankaHesabiId")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FisTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("KasaHesabiId")
                        .HasColumnType("integer");

                    b.Property<int>("OdemeYontemi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankaHesabiId");

                    b.HasIndex("CariId");

                    b.HasIndex("FisNo")
                        .IsUnique();

                    b.HasIndex("KasaHesabiId");

                    b.ToTable("CariFisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.CekSenet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAdi")
                        .HasColumnType("text");

                    b.Property<string>("BelgeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BelgeTipi")
                        .HasColumnType("integer");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<string>("CiroBilgisi")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("text");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("VadeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("CekSenetler");
                });

            modelBuilder.Entity("SakaryaERP.Models.HesapPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("HesapAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HesapTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("HesapKodu")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("HesapPlani");
                });

            modelBuilder.Entity("SakaryaERP.Models.KasaHesabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KasaHesaplari");
                });

            modelBuilder.Entity("SakaryaERP.Models.Malzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Bakiye")
                        .HasColumnType("numeric");

                    b.Property<string>("Barkod")
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kalite")
                        .HasColumnType("text");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MalzemeKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marka")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxStokMiktari")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinStokMiktari")
                        .HasColumnType("numeric");

                    b.Property<string>("RafNo")
                        .HasColumnType("text");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("numeric");

                    b.Property<int>("StokTipi")
                        .HasColumnType("integer");

                    b.Property<int>("TeminTuru")
                        .HasColumnType("integer");

                    b.Property<string>("Tip")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("MalzemeKodu")
                        .IsUnique();

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeHareketFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("FisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HareketTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("MalzemeHareketFisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeHareketFisiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MalzemeHareketFisiId")
                        .HasColumnType("integer");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeHareketFisiId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("MalzemeHareketFisiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MalzemeKategoriler");
                });

            modelBuilder.Entity("SakaryaERP.Models.MuhasebeFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlisFaturasiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SatisFaturasiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlisFaturasiId")
                        .IsUnique();

                    b.HasIndex("SatisFaturasiId")
                        .IsUnique();

                    b.ToTable("MuhasebeFisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.MuhasebeFisiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Borc")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("HesapPlaniId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MuhasebeFisiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("HesapPlaniId");

                    b.HasIndex("MuhasebeFisiId");

                    b.ToTable("MuhasebeFisiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.MusteriTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TalepNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.ToTable("MusteriTalepleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisFaturasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SatisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<int?>("SevkIrsaliyesiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("SatisSiparisiId");

                    b.HasIndex("SevkIrsaliyesiId");

                    b.ToTable("SatisFaturalari");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisFaturasiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("SatisFaturasiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("SatisFaturasiId");

                    b.ToTable("SatisFaturasiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisSiparisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SatisTeklifiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("SatisTeklifiId");

                    b.ToTable("SatisSiparisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisSiparisiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("SatisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("SatisSiparisiId");

                    b.ToTable("SatisSiparisiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisTeklifi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CariId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MusteriTalebiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CariId");

                    b.HasIndex("MusteriTalebiId");

                    b.ToTable("SatisTeklifleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisTeklifiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Iskonto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("SatisTeklifiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("SatisTeklifiId");

                    b.ToTable("SatisTeklifiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SevkIrsaliyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AracSofor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SatisSiparisiId")
                        .HasColumnType("integer");

                    b.Property<string>("SevkAdresi")
                        .HasColumnType("text");

                    b.Property<int>("SubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SatisSiparisiId");

                    b.HasIndex("SubeId");

                    b.ToTable("SevkIrsaliyeleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SevkIrsaliyesiKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<int>("SevkIrsaliyesiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("SevkIrsaliyesiId");

                    b.ToTable("SevkIrsaliyesiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SakaryaERP.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SakaryaERP.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SakaryaERP.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SakaryaERP.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SakaryaERP.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisFaturasi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisIrsaliyesi", "AlisIrsaliyesi")
                        .WithMany("AlisFaturalari")
                        .HasForeignKey("AlisIrsaliyesiId");

                    b.HasOne("SakaryaERP.Models.AlisSiparisi", "AlisSiparisi")
                        .WithMany("AlisFaturalari")
                        .HasForeignKey("AlisSiparisiId");

                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("AlisFaturalari")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisIrsaliyesi");

                    b.Navigation("AlisSiparisi");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisFaturasiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisFaturasi", "AlisFaturasi")
                        .WithMany("Kalemler")
                        .HasForeignKey("AlisFaturasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisFaturasi");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisIrsaliyesi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisSiparisi", "AlisSiparisi")
                        .WithMany("AlisIrsaliyeleri")
                        .HasForeignKey("AlisSiparisiId");

                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("AlisIrsaliyeleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Sube", "Sube")
                        .WithMany("AlisIrsaliyeleri")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisSiparisi");

                    b.Navigation("Cari");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisIrsaliyesiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisIrsaliyesi", "AlisIrsaliyesi")
                        .WithMany("Kalemler")
                        .HasForeignKey("AlisIrsaliyesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisIrsaliyesi");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisSiparisi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisTeklifi", "AlisTeklifi")
                        .WithMany("AlisSiparisleri")
                        .HasForeignKey("AlisTeklifiId");

                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("AlisSiparisleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Sube", "Sube")
                        .WithMany("AlisSiparisleri")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisTeklifi");

                    b.Navigation("Cari");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisSiparisiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisSiparisi", "AlisSiparisi")
                        .WithMany("Kalemler")
                        .HasForeignKey("AlisSiparisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisSiparisi");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTalebi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTeklifi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisTalebi", "AlisTalebi")
                        .WithMany("AlisTeklifleri")
                        .HasForeignKey("AlisTalebiId");

                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisTalebi");

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTeklifiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisTeklifi", "AlisTeklifi")
                        .WithMany("Kalemler")
                        .HasForeignKey("AlisTeklifiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlisTeklifi");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("SakaryaERP.Models.AppUser", b =>
                {
                    b.HasOne("SakaryaERP.Models.Sube", "Sube")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("SakaryaERP.Models.CariFisi", b =>
                {
                    b.HasOne("SakaryaERP.Models.BankaHesabi", "BankaHesabi")
                        .WithMany("CariFisleri")
                        .HasForeignKey("BankaHesabiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("CariFisleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.KasaHesabi", "KasaHesabi")
                        .WithMany("CariFisleri")
                        .HasForeignKey("KasaHesabiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BankaHesabi");

                    b.Navigation("Cari");

                    b.Navigation("KasaHesabi");
                });

            modelBuilder.Entity("SakaryaERP.Models.CekSenet", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("CekSenetler")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("SakaryaERP.Models.HesapPlani", b =>
                {
                    b.HasOne("SakaryaERP.Models.HesapPlani", "Parent")
                        .WithMany("AltHesaplar")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SakaryaERP.Models.Malzeme", b =>
                {
                    b.HasOne("SakaryaERP.Models.MalzemeKategori", "Kategori")
                        .WithMany("Malzemeler")
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeHareketFisi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Sube", "Sube")
                        .WithMany("MalzemeHareketFisleri")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeHareketFisiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.MalzemeHareketFisi", "MalzemeHareketFisi")
                        .WithMany("Kalemler")
                        .HasForeignKey("MalzemeHareketFisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany("HareketKalemleri")
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("MalzemeHareketFisi");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeKategori", b =>
                {
                    b.HasOne("SakaryaERP.Models.MalzemeKategori", "Parent")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SakaryaERP.Models.MuhasebeFisi", b =>
                {
                    b.HasOne("SakaryaERP.Models.AlisFaturasi", "AlisFaturasi")
                        .WithOne("MuhasebeFisi")
                        .HasForeignKey("SakaryaERP.Models.MuhasebeFisi", "AlisFaturasiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SakaryaERP.Models.SatisFaturasi", "SatisFaturasi")
                        .WithOne("MuhasebeFisi")
                        .HasForeignKey("SakaryaERP.Models.MuhasebeFisi", "SatisFaturasiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlisFaturasi");

                    b.Navigation("SatisFaturasi");
                });

            modelBuilder.Entity("SakaryaERP.Models.MuhasebeFisiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.HesapPlani", "HesapPlani")
                        .WithMany("MuhasebeFisiKalemleri")
                        .HasForeignKey("HesapPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.MuhasebeFisi", "MuhasebeFisi")
                        .WithMany("Kalemler")
                        .HasForeignKey("MuhasebeFisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HesapPlani");

                    b.Navigation("MuhasebeFisi");
                });

            modelBuilder.Entity("SakaryaERP.Models.MusteriTalebi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("MusteriTalepleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cari");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisFaturasi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SatisSiparisi", "SatisSiparisi")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("SatisSiparisiId");

                    b.HasOne("SakaryaERP.Models.SevkIrsaliyesi", "SevkIrsaliyesi")
                        .WithMany("SatisFaturalari")
                        .HasForeignKey("SevkIrsaliyesiId");

                    b.Navigation("Cari");

                    b.Navigation("SatisSiparisi");

                    b.Navigation("SevkIrsaliyesi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisFaturasiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SatisFaturasi", "SatisFaturasi")
                        .WithMany("Kalemler")
                        .HasForeignKey("SatisFaturasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("SatisFaturasi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisSiparisi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("SatisSiparisleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SatisTeklifi", "SatisTeklifi")
                        .WithMany("SatisSiparisleri")
                        .HasForeignKey("SatisTeklifiId");

                    b.Navigation("Cari");

                    b.Navigation("SatisTeklifi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisSiparisiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SatisSiparisi", "SatisSiparisi")
                        .WithMany("Kalemler")
                        .HasForeignKey("SatisSiparisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("SatisSiparisi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisTeklifi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Cari", "Cari")
                        .WithMany("SatisTeklifleri")
                        .HasForeignKey("CariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.MusteriTalebi", "MusteriTalebi")
                        .WithMany("SatisTeklifleri")
                        .HasForeignKey("MusteriTalebiId");

                    b.Navigation("Cari");

                    b.Navigation("MusteriTalebi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisTeklifiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SatisTeklifi", "SatisTeklifi")
                        .WithMany("Kalemler")
                        .HasForeignKey("SatisTeklifiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("SatisTeklifi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SevkIrsaliyesi", b =>
                {
                    b.HasOne("SakaryaERP.Models.SatisSiparisi", "SatisSiparisi")
                        .WithMany("SevkIrsaliyeleri")
                        .HasForeignKey("SatisSiparisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.Sube", "Sube")
                        .WithMany("SevkIrsaliyeleri")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SatisSiparisi");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("SakaryaERP.Models.SevkIrsaliyesiKalemi", b =>
                {
                    b.HasOne("SakaryaERP.Models.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakaryaERP.Models.SevkIrsaliyesi", "SevkIrsaliyesi")
                        .WithMany("Kalemler")
                        .HasForeignKey("SevkIrsaliyesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("SevkIrsaliyesi");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisFaturasi", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("MuhasebeFisi");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisIrsaliyesi", b =>
                {
                    b.Navigation("AlisFaturalari");

                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisSiparisi", b =>
                {
                    b.Navigation("AlisFaturalari");

                    b.Navigation("AlisIrsaliyeleri");

                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTalebi", b =>
                {
                    b.Navigation("AlisTeklifleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.AlisTeklifi", b =>
                {
                    b.Navigation("AlisSiparisleri");

                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("SakaryaERP.Models.BankaHesabi", b =>
                {
                    b.Navigation("CariFisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.Cari", b =>
                {
                    b.Navigation("AlisFaturalari");

                    b.Navigation("AlisIrsaliyeleri");

                    b.Navigation("AlisSiparisleri");

                    b.Navigation("CariFisleri");

                    b.Navigation("CekSenetler");

                    b.Navigation("MusteriTalepleri");

                    b.Navigation("SatisFaturalari");

                    b.Navigation("SatisSiparisleri");

                    b.Navigation("SatisTeklifleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.HesapPlani", b =>
                {
                    b.Navigation("AltHesaplar");

                    b.Navigation("MuhasebeFisiKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.KasaHesabi", b =>
                {
                    b.Navigation("CariFisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.Malzeme", b =>
                {
                    b.Navigation("HareketKalemleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeHareketFisi", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("SakaryaERP.Models.MalzemeKategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Malzemeler");
                });

            modelBuilder.Entity("SakaryaERP.Models.MuhasebeFisi", b =>
                {
                    b.Navigation("Kalemler");
                });

            modelBuilder.Entity("SakaryaERP.Models.MusteriTalebi", b =>
                {
                    b.Navigation("SatisTeklifleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisFaturasi", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("MuhasebeFisi");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisSiparisi", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("SatisFaturalari");

                    b.Navigation("SevkIrsaliyeleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SatisTeklifi", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("SatisSiparisleri");
                });

            modelBuilder.Entity("SakaryaERP.Models.SevkIrsaliyesi", b =>
                {
                    b.Navigation("Kalemler");

                    b.Navigation("SatisFaturalari");
                });

            modelBuilder.Entity("SakaryaERP.Models.Sube", b =>
                {
                    b.Navigation("AlisIrsaliyeleri");

                    b.Navigation("AlisSiparisleri");

                    b.Navigation("Kullanicilar");

                    b.Navigation("MalzemeHareketFisleri");

                    b.Navigation("SevkIrsaliyeleri");
                });
#pragma warning restore 612, 618
        }
    }
}
